services:
    micogian.forum_readers.listener:
        class: micogian\forum_readers\event\listener
        arguments:
            - @dbal.conn
            - @template
            - @auth
            - @user
            - %core.root_path%
        tags:
            - { name: event.listener }
